### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by mindjek007** [abhira0/pyscrolller#5]
C:\Users\user\Downloads\pyscrolller-main>python pyscrolller.py -s lesbianasslick --download
Exception in thread Thread-21:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\user\Downloads\pyscrolller-main\pyscrolller.py", line 213, in processSubResponse
    children_items = self.querySubreddit()
  File "C:\Users\user\Downloads\pyscrolller-main\pyscrolller.py", line 245, in querySubreddit
Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 973, in _bootstrap_inner
    children_items = response_json["data"]["getSubreddit"]["children"]["items"]
TypeError: 'NoneType' object is not subscriptable
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\user\Downloads\pyscrolller-main\pyscrolller.py", line 213, in processSubResponse
Exception in thread Thread-4:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 973, in _bootstrap_inner
    children_items = self.querySubreddit()
  File "C:\Users\user\Downloads\pyscrolller-main\pyscrolller.py", line 245, in querySubreddit
    self.run()
    children_items = response_json["data"]["getSubreddit"]["children"]["items"]
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 910, in run
TypeError: 'NoneType' object is not subscriptable
    self._target(*self._args, **self._kwargs)
  File "C:\Users\user\Downloads\pyscrolller-main\pyscrolller.py", line 213, in processSubResponse
    children_items = self.querySubreddit()
  File "C:\Users\user\Downloads\pyscrolller-main\pyscrolller.py", line 245, in querySubreddit
    children_items = response_json["data"]["getSubreddit"]["children"]["items"]
TypeError: 'NoneType' object is not subscriptable
Exception in thread Thread-5:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 910, in run
Exception in thread Thread-8:
    self._target(*self._args, **self._kwargs)
Traceback (most recent call last):
  File "C:\Users\user\Downloads\pyscrolller-main\pyscrolller.py", line 213, in processSubResponse
Exception in thread Thread-10:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 973, in _bootstrap_inner
Exception in thread Thread-24:
Traceback (most recent call last):
Exception in thread Thread-7:
Exception in thread Thread-16:
Traceback (most recent call last):
Exception in thread Thread-18:
Exception in thread Thread-20:
Exception in thread Thread-12:
Exception in thread Thread-29:
Exception in thread Thread-11:
Exception in thread Thread-30:
Exception in thread Thread-14:
Traceback (most recent call last):
    children_items = self.querySubreddit()
Exception in thread Thread-22:
Exception in thread Thread-31:
Exception in thread Thread-28:
Exception in thread Thread-25:
Exception in thread Thread-19:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 973, in _bootstrap_inner
Exception in thread Thread-9:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 910, in run
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 973, in _bootstrap_inner
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 973, in _bootstrap_inner
Traceback (most recent call last):
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 973, in _bootstrap_inner
Traceback (most recent call last):
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 973, in _bootstrap_inner
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 973, in _bootstrap_inner
Exception in thread Thread-23:
  File "C:\Users\user\Downloads\pyscrolller-main\pyscrolller.py", line 245, in querySubreddit
Exception in thread Thread-15:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 973, in _bootstrap_inner
Traceback (most recent call last):
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 910, in run
Exception in thread Thread-27:
Traceback (most recent call last):
    self.run()
    self._target(*self._args, **self._kwargs)
  File "C:\Users\user\Downloads\pyscrolller-main\pyscrolller.py", line 213, in processSubResponse
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 973, in _bootstrap_inner
Exception in thread Thread-6:
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 910, in run
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 910, in run
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 910, in run
    children_items = response_json["data"]["getSubreddit"]["children"]["items"]
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 973, in _bootstrap_inner
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 910, in run
    self.run()
    self._target(*self._args, **self._kwargs)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 973, in _bootstrap_inner
    self._target(*self._args, **self._kwargs)
  File "C:\Users\user\Downloads\pyscrolller-main\pyscrolller.py", line 213, in processSubResponse
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 910, in run
Traceback (most recent call last):
    children_items = self.querySubreddit()
  File "C:\Users\user\Downloads\pyscrolller-main\pyscrolller.py", line 245, in querySubreddit
Exception in thread Thread-13:
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 973, in _bootstrap_inner
Traceback (most recent call last):
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
Traceback (most recent call last):
    self.run()
    self.run()
    children_items = self.querySubreddit()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 973, in _bootstrap_inner
    self._target(*self._args, **self._kwargs)
    self.run()
    children_items = response_json["data"]["getSubreddit"]["children"]["items"]
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\Users\user\Downloads\pyscrolller-main\pyscrolller.py", line 213, in processSubResponse
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 973, in _bootstrap_inner
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 910, in run
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 910, in run
  File "C:\Users\user\Downloads\pyscrolller-main\pyscrolller.py", line 245, in querySubreddit
    self.run()
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 910, in run
TypeError: 'NoneType' object is not subscriptable
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 973, in _bootstrap_inner
  File "C:\Users\user\Downloads\pyscrolller-main\pyscrolller.py", line 213, in processSubResponse
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 973, in _bootstrap_inner
    self._target(*self._args, **self._kwargs)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 910, in run
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 910, in run
    self.run()
  File "C:\Users\user\Downloads\pyscrolller-main\pyscrolller.py", line 213, in processSubResponse
    self._target(*self._args, **self._kwargs)
    children_items = self.querySubreddit()
    self.run()
    self.run()
    self._target(*self._args, **self._kwargs)
  File "C:\Users\user\Downloads\pyscrolller-main\pyscrolller.py", line 213, in processSubResponse
  File "C:\Users\user\Downloads\pyscrolller-main\pyscrolller.py", line 213, in processSubResponse
    children_items = response_json["data"]["getSubreddit"]["children"]["items"]
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 910, in run
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\user\Downloads\pyscrolller-main\pyscrolller.py", line 213, in processSubResponse
    children_items = self.querySubreddit()
TypeError: 'NoneType' object is not subscriptable
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 910, in run
  File "C:\Users\user\Downloads\pyscrolller-main\pyscrolller.py", line 213, in processSubResponse
    children_items = self.querySubreddit()
    children_items = self.querySubreddit()
    self._target(*self._args, **self._kwargs)
  File "C:\Users\user\Downloads\pyscrolller-main\pyscrolller.py", line 213, in processSubResponse
    self._target(*self._args, **self._kwargs)
  File "C:\Users\user\Downloads\pyscrolller-main\pyscrolller.py", line 213, in processSubResponse
  File "C:\Users\user\Downloads\pyscrolller-main\pyscrolller.py", line 245, in querySubreddit
  File "C:\Users\user\Downloads\pyscrolller-main\pyscrolller.py", line 245, in querySubreddit
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\user\Downloads\pyscrolller-main\pyscrolller.py", line 213, in processSubResponse
    self._target(*self._args, **self._kwargs)
  File "C:\Users\user\Downloads\pyscrolller-main\pyscrolller.py", line 245, in querySubreddit
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 973, in _bootstrap_inner
    children_items = response_json["data"]["getSubreddit"]["children"]["items"]
    children_items = self.querySubreddit()
  File "C:\Users\user\Downloads\pyscrolller-main\pyscrolller.py", line 245, in querySubreddit
    children_items = self.querySubreddit()
    children_items = response_json["data"]["getSubreddit"]["children"]["items"]
TypeError: 'NoneType' object is not subscriptable
    children_items = self.querySubreddit()
  File "C:\Users\user\Downloads\pyscrolller-main\pyscrolller.py", line 245, in querySubreddit
  File "C:\Users\user\Downloads\pyscrolller-main\pyscrolller.py", line 245, in querySubreddit
    self.run()
TypeError: 'NoneType' object is not subscriptable
  File "C:\Users\user\Downloads\pyscrolller-main\pyscrolller.py", line 213, in processSubResponse
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 910, in run
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 910, in run
    children_items = response_json["data"]["getSubreddit"]["children"]["items"]
TypeError: 'NoneType' object is not subscriptable
    children_items = self.querySubreddit()
    children_items = self.querySubreddit()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    children_items = self.querySubreddit()
    self.run()
TypeError: 'NoneType' object is not subscriptable
    self._target(*self._args, **self._kwargs)
    children_items = response_json["data"]["getSubreddit"]["children"]["items"]
    children_items = response_json["data"]["getSubreddit"]["children"]["items"]
    self.run()
  File "C:\Users\user\Downloads\pyscrolller-main\pyscrolller.py", line 213, in processSubResponse
    self._target(*self._args, **self._kwargs)
  File "C:\Users\user\Downloads\pyscrolller-main\pyscrolller.py", line 245, in querySubreddit
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 910, in run
  File "C:\Users\user\Downloads\pyscrolller-main\pyscrolller.py", line 245, in querySubreddit
  File "C:\Users\user\Downloads\pyscrolller-main\pyscrolller.py", line 245, in querySubreddit
  File "C:\Users\user\Downloads\pyscrolller-main\pyscrolller.py", line 245, in querySubreddit
    children_items = response_json["data"]["getSubreddit"]["children"]["items"]
    children_items = self.querySubreddit()
    self._target(*self._args, **self._kwargs)
    children_items = response_json["data"]["getSubreddit"]["children"]["items"]
  File "C:\Users\user\Downloads\pyscrolller-main\pyscrolller.py", line 213, in processSubResponse
    self._target(*self._args, **self._kwargs)
TypeError: 'NoneType' object is not subscriptable
    children_items = response_json["data"]["getSubreddit"]["children"]["items"]
    children_items = response_json["data"]["getSubreddit"]["children"]["items"]
  File "C:\Users\user\Downloads\pyscrolller-main\pyscrolller.py", line 213, in processSubResponse
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 910, in run
  File "C:\Users\user\Downloads\pyscrolller-main\pyscrolller.py", line 213, in processSubResponse
TypeError: 'NoneType' object is not subscriptable
TypeError: 'NoneType' object is not subscriptable
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 910, in run
    children_items = self.querySubreddit()
  File "C:\Users\user\Downloads\pyscrolller-main\pyscrolller.py", line 245, in querySubreddit
  File "C:\Users\user\Downloads\pyscrolller-main\pyscrolller.py", line 245, in querySubreddit
    children_items = self.querySubreddit()
  File "C:\Users\user\Downloads\pyscrolller-main\pyscrolller.py", line 245, in querySubreddit
  File "C:\Users\user\Downloads\pyscrolller-main\pyscrolller.py", line 213, in processSubResponse
    children_items = response_json["data"]["getSubreddit"]["children"]["items"]
    self._target(*self._args, **self._kwargs)
TypeError: 'NoneType' object is not subscriptable
    children_items = response_json["data"]["getSubreddit"]["children"]["items"]
TypeError: 'NoneType' object is not subscriptable
    children_items = response_json["data"]["getSubreddit"]["children"]["items"]
TypeError: 'NoneType' object is not subscriptable
  File "C:\Users\user\Downloads\pyscrolller-main\pyscrolller.py", line 213, in processSubResponse
  File "C:\Users\user\Downloads\pyscrolller-main\pyscrolller.py", line 213, in processSubResponse
  File "C:\Users\user\Downloads\pyscrolller-main\pyscrolller.py", line 213, in processSubResponse
    self._target(*self._args, **self._kwargs)
  File "C:\Users\user\Downloads\pyscrolller-main\pyscrolller.py", line 213, in processSubResponse
TypeError: 'NoneType' object is not subscriptable
    children_items = self.querySubreddit()
  File "C:\Users\user\Downloads\pyscrolller-main\pyscrolller.py", line 245, in querySubreddit
TypeError: 'NoneType' object is not subscriptable
    self._target(*self._args, **self._kwargs)
    children_items = response_json["data"]["getSubreddit"]["children"]["items"]
    children_items = self.querySubreddit()
  File "C:\Users\user\Downloads\pyscrolller-main\pyscrolller.py", line 245, in querySubreddit
    children_items = self.querySubreddit()
  File "C:\Users\user\Downloads\pyscrolller-main\pyscrolller.py", line 245, in querySubreddit
    children_items = self.querySubreddit()
  File "C:\Users\user\Downloads\pyscrolller-main\pyscrolller.py", line 245, in querySubreddit
    children_items = response_json["data"]["getSubreddit"]["children"]["items"]
  File "C:\Users\user\Downloads\pyscrolller-main\pyscrolller.py", line 213, in processSubResponse
TypeError: 'NoneType' object is not subscriptable
TypeError: 'NoneType' object is not subscriptable
    children_items = response_json["data"]["getSubreddit"]["children"]["items"]
TypeError: 'NoneType' object is not subscriptable
    children_items = self.querySubreddit()
TypeError: 'NoneType' object is not subscriptable
    children_items = self.querySubreddit()
  File "C:\Users\user\Downloads\pyscrolller-main\pyscrolller.py", line 245, in querySubreddit
    children_items = response_json["data"]["getSubreddit"]["children"]["items"]
TypeError: 'NoneType' object is not subscriptable
    children_items = response_json["data"]["getSubreddit"]["children"]["items"]
    children_items = response_json["data"]["getSubreddit"]["children"]["items"]
    children_items = self.querySubreddit()
TypeError: 'NoneType' object is not subscriptable
TypeError: 'NoneType' object is not subscriptable
  File "C:\Users\user\Downloads\pyscrolller-main\pyscrolller.py", line 245, in querySubreddit
    children_items = self.querySubreddit()
  File "C:\Users\user\Downloads\pyscrolller-main\pyscrolller.py", line 245, in querySubreddit
  File "C:\Users\user\Downloads\pyscrolller-main\pyscrolller.py", line 245, in querySubreddit
    children_items = response_json["data"]["getSubreddit"]["children"]["items"]
TypeError: 'NoneType' object is not subscriptable
    children_items = response_json["data"]["getSubreddit"]["children"]["items"]
    children_items = response_json["data"]["getSubreddit"]["children"]["items"]
TypeError: 'NoneType' object is not subscriptable
TypeError: 'NoneType' object is not subscriptable
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\user\Downloads\pyscrolller-main\pyscrolller.py", line 213, in processSubResponse
    children_items = self.querySubreddit()
  File "C:\Users\user\Downloads\pyscrolller-main\pyscrolller.py", line 245, in querySubreddit
    children_items = response_json["data"]["getSubreddit"]["children"]["items"]
TypeError: 'NoneType' object is not subscriptable
Exception in thread Thread-26:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\user\Downloads\pyscrolller-main\pyscrolller.py", line 213, in processSubResponse
    children_items = self.querySubreddit()
  File "C:\Users\user\Downloads\pyscrolller-main\pyscrolller.py", line 245, in querySubreddit
    children_items = response_json["data"]["getSubreddit"]["children"]["items"]
TypeError: 'NoneType' object is not subscriptable
Exception in thread Thread-17:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\user\Downloads\pyscrolller-main\pyscrolller.py", line 213, in processSubResponse
    children_items = self.querySubreddit()
  File "C:\Users\user\Downloads\pyscrolller-main\pyscrolller.py", line 245, in querySubreddit
    children_items = response_json["data"]["getSubreddit"]["children"]["items"]
TypeError: 'NoneType' object is not subscriptable

**Comment by abhira0** [comment]
A minor change in the scrolller query caused the issue

This project has evolved into a new unified project, so I request to use the following project 
 https://github.com/abhira0/dbscr
